---
title: 'Florida Geological Survey: WKP Statistical Atlas'
author: "Seth Bassett, GISP"
date: "September 20, 2015"
output:
  html_document:
    toc: yes
    toc_depth: 3
    theme: united
    number_sections: false
---

# Introduction

This project chronicles the analysis of the Florida Geological Survey's Woodville Karst Plain instrumentation project. All coding and documents were created as part of the Karst Open Research Iniative (KORI).

# Conduit Analysis  
  
* [B Conduit](conduit_analysis/b_conduit.html)  
* [C Conduit](conduit_analysis/c_conduit.html)
* [D Conduit](conduit_analysis/d_conduit.html)

# Cross-conduit Analysis  
  
# Interactive Visualizations
All interactive visualizations are experimental.  
  
* Dygraphs
    + [Falmouth 2D-ACM ASPD](interactive/dygraphs/aspd/index.html)  
    + [Falmouth 2D-ACM COND](interactive/dygraphs/cond/index.html)  
    + [Falmouth 2D-ACM AVDIR](interactive/dygraphs/avdir/index.html)  
    + [Falmouth 2D-ACM TEMP](interactive/dygraphs/temp/index.html)  
    + [Falmouth 2D-ACM PRES](interactive/dygraphs/pres/index.html)  
* threejs
    + [Wakulla Structured Contours, Limestone Units](interactive/threejs/structured_contours/index.html)

# Presentations  
  
* [FSU Woodville Karst Plain Research Workshop](presentations/fsu_20150925/index.html)

Contact: Seth [adot] Bassett [at_symbol] dep [adot] state [adot] fl [adot] us
